version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

commands:
  build_test:
    description: Install dependencies and run tests
    steps:
      - checkout

      - run: sudo apt update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit
      - run: ./vendor/bin/behat -f progress -o std -f junit -o test-results/behat
      - run: ./vendor/bin/psalm --show-info=false

      - store_test_results:
          path: test-results

      # CODECOV_TOKEN defined in project configuration
      - codecov/upload:
          file: test-results/phpunit/coverage.xml

jobs:
  build_test_71:
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - build_test

  build_test_72:
    docker:
      - image: circleci/php:7.2-cli
    steps:
      - build_test

  build_test_73:
    docker:
      - image: circleci/php:7.3-cli
    steps:
      - build_test

  build_test_74:
    docker:
      - image: circleci/php:7.4-cli
    steps:
      - build_test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_test_71
      - build_test_72
      - build_test_73
      - build_test_74