services:

  acpr.behat.psr.context.initializer:
    class: Acpr\Behat\Psr\Context\Initializer\ContextInitializer
    arguments:
      - "@acpr.behat.psr.factory"
      - "@acpr.behat.psr.kernel"
      - '%mink.base_url%'
    tags:
      - { name: context.initializer }

  acpr.behat.psr.client:
    class: Symfony\Component\HttpKernel\HttpKernelBrowser
    arguments: [ "@acpr.behat.psr.kernel" ]

  acpr.behat.psr.kernel:
    class: Acpr\Behat\Psr\RuntimeConfigurableTranslatorKernel
    shared: false
    arguments:
      - "@acpr.behat.psr.translator"

  acpr.behat.psr.translator:
    class: Acpr\Behat\Psr\SymfonyPsrTranslator
    arguments:
      - "@acpr.behat.psr.translator.httpfoundationfactory"
      - "@acpr.behat.psr.translator.psrhttpfactory"

  acpr.behat.psr.translator.httpfoundationfactory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory

  acpr.behat.psr.translator.psrhttpfactory:
    class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory
    arguments:
      - "@Zend\\Diactoros\\ServerRequestFactory"
      - "@Zend\\Diactoros\\StreamFactory"
      - "@Zend\\Diactoros\\UploadedFileFactory"
      - "@Zend\\Diactoros\\ResponseFactory"

  Zend\Diactoros\ServerRequestFactory: ~
  Zend\Diactoros\StreamFactory: ~
  Zend\Diactoros\UploadedFileFactory: ~
  Zend\Diactoros\ResponseFactory: ~