services:

  acpr.behat.psr.factory:
    class: Acpr\Behat\Psr\ServiceContainer\Factory\PsrFactory
    shared: true
    arguments:
      - '%acpr.behat.psr.container.file%'
      - '%acpr.behat.psr.application.file%'

  acpr.behat.psr.context.initializer:
    class: Acpr\Behat\Psr\Context\Initializer\ContextInitializer
    arguments:
      - "@acpr.behat.psr.factory"
      - "@acpr.behat.psr.mink-session-factory"
      - "@acpr.behat.psr.kernel"
    tags:
      - { name: context.initializer }

  acpr.behat.psr.client:
    class: Symfony\Component\HttpKernel\HttpKernelBrowser
    arguments: [ "@acpr.behat.psr.kernel" ]

  acpr.behat.psr.mink-session-factory:
    class: Acpr\Behat\Psr\ServiceContainer\Factory\MinkSessionFactory
    shared: true
    arguments: [ "%mink.base_url" ]

  acpr.behat.psr.kernel:
    class: Acpr\Behat\Psr\RuntimeConfigurableTranslatorKernel
    shared: false
    arguments:
      - "@acpr.behat.psr.translator"

  acpr.behat.psr.translator:
    class: Acpr\Behat\Psr\SymfonyPsrTranslator
    arguments:
      - "@Symfony\\Bridge\\PsrHttpMessage\\Factory\\HttpFoundationFactory"
      - "@Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory"

  Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~
  Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory:
    arguments:
      - "@Zend\\Diactoros\\ServerRequestFactory"
      - "@Zend\\Diactoros\\StreamFactory"
      - "@Zend\\Diactoros\\UploadedFileFactory"
      - "@Zend\\Diactoros\\ResponseFactory"

  Zend\Diactoros\ServerRequestFactory: ~
  Zend\Diactoros\StreamFactory: ~
  Zend\Diactoros\UploadedFileFactory: ~
  Zend\Diactoros\ResponseFactory: ~